### PR TITLE
Added Typescript ( react-fullpage.d.ts ) to the dist folder (PLEASE ACCEPT)

### PR DESCRIPTION
**Pull request by AbobkerElaghel**
Please accept, Some (IAAS) Infrastructure as a service platforms build the projects on every push, it fails the build process because of a typescript error for everyone that uses typescript with React fullPage.

+ You can't really work with fullpage in a typescript environment without manually adding the file in this pull request.
please do accept this file to fix the problem and for developers like me to avoid manual patching to work in typescript

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Is the `dist` the right folder for it?  🤔

**Comment by AbobkerElaghel** [comment]
Yes, it is, when pasting the file there all typescript errors disappear.
as seen below, I had to write a copy command to copy the types file to its destination (dist).

**Comment by alvarotrigo** [comment]
I think a better place can be in a folder called `./types` on the root folder.
Same as in [this repo](filepond).

If you can make the change I'll merge it.

**Comment by alvarotrigo** [comment]
Shouldn't you be importing it on your code?

**Comment by AbobkerElaghel** [comment]
If u are talking about the types file, No.
it should import the types automatically like all other repos.
your only concern is to import the package to use it.

**Comment by alvarotrigo** [comment]
Have you tried renaming it to for example `types/index.d.ts` instead? 
It might be related with [this](https://stackoverflow.com/a/59728984/1081396)?

We'd also have to add it on the `package.json` file as `"types": "types/index.d.ts",`
See an example [here](https://github.com/pqina/filepond/blob/master/package.json#L37).

**Comment by AbobkerElaghel** [comment]
Yap, This fixed it.
- Renamed the file to `index.d.ts`
- moved it to `types` dir in the root dir
- Added `"types": "types/index.d.ts"` TO `package.json`

**Comment by patcheco1001** [comment]
Thank you @AbobkerElaghel for your works and effort.
Could you please make the **Item** object exportable ? This object is not just used internally as you know but also returned in the listeners onLeave, afterLoad and afterSlideLoad
It's a quick fix : replace **type Item** with **export type Item**

**Pull request closed without merging**
