### PR TITLE
Added Typescript types to `react-fullpage`

### PR DESCRIPTION
**Pull request by AbobkerElaghel**
1. Make sure to commit it to the `dev` branch!
2. Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js

- Created a dir `types ` in the root dir
- Created a typescript file to fixed the types error when using typescript `types/index.d.ts`
- Modified package to recognize the `types/index.d.ts`
-.Added `"types": "types/index.d.ts"` TO `package.json`

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for that @AbobkerElaghel ! 👍

**Comment by AbobkerElaghel** [comment]
Thank you for merging and for the information!! @alvarotrigo 👍

**Comment by AbobkerElaghel** [comment]
When are you going to merge it to the master branch?

**Comment by AbobkerElaghel** [comment]
Thanks so much..

**Pull request merged**
