### PR TITLE
Flatten callbacks, update example with class component

### PR DESCRIPTION
**Pull request by cmswalker**
This should handle https://github.com/alvarotrigo/react-fullpage/issues/22

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Awesome! Thanks for that @cmswalker !

So, in order to use a callback, would we have to always use the following structure?

```javascript
onLeave={this.onLeave.bind(this)}
afterLoad={this.afterLoad.bind(this)}
...
``` 

And add them too outside the `render` function?

```javascript
onLeave(origin, destination, direction) { // arguments are mapped in order of fullpage.js callback arguments
  sectionsColor: ['#282c34', '#ff5f45', '#0798ec'],	    // do something with the event
  callbacks: ['onLeave'],	  }
```

**Comment by cmswalker** [comment]
Yes that's probably the usual way most would want to use so they can trigger events/state changes when the callbacks are invoked. Alternatively they could just be global functions if no class/instance methods are necessary as well, but this is a little less common in react.

**Comment by alvarotrigo** [comment]
Yeap sounds good! Noticed a similar behaviour in other components like [Froala editor wrapper for React](https://github.com/froala/react-froala-wysiwyg#displaying-html).

**Comment by cmswalker** [comment]
Noting that we'll want to do a minor patch for this one

**Comment by alvarotrigo** [comment]
After the latest releases it seems we have some conflicts here to resolve.

**Pull request merged**
