### PR TITLE
Added Typescript support

### PR DESCRIPTION
**Pull request by Hexidecibel**
Added necessary devDependencies, typescript bindings file (from issue #163 ), and reference to it in package.json.  

The type definition file was added directly to ./dist.  If you clear this dir on builds - this could be a problem.  In that case it can be copied into this dir as part of build.  I tried to limit changes to actual dependencies to limit impact to project.  Depending on your build process you may or may not agree with my choices.

One gripe I have is that state is still using any, would be nice to define what 'state' is in the render function for FullPageProps.  It's fine as is I guess, just need to suppress warnings.

Verified this is working from consuming application.  

1. Make sure to commit it to the `dev` branch! ✅
2. Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js ✅

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Any reason why this got closed?

**Comment by Hexidecibel** [comment]
Ah.  I was cleaning up repos on my account and looks like I accidentally deleted the fork the pr was on and it auto closed the pr.  I can recreate it if you'd like.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alvarotrigo** [comment]
> I can recreate it if you'd like.

That'd be great, happy to merge this ;)

**Comment by Hexidecibel** [comment]
Reopened!  Looks like it has conflicts now and I am unable to resolve, so hopefully you can handle that!

**Comment by alvarotrigo** [comment]
I realized this was already present in the `/types` folder:
https://github.com/alvarotrigo/react-fullpage/tree/master/types

**Pull request closed without merging**
