### PR TITLE
Made cards and cards Options Props optional because they cause a build time (Type Check) error in typescript when not being specified explicitly

### PR DESCRIPTION
**Pull request by AbobkerElaghel**
1. Make sure to commit it to the `dev` branch!
2. Read https://github.com/alvarotrigo/fullPage.js/wiki/Contributing-to-fullpage.js

### CODE REVIEW

**Comment by alvarotrigo** [comment]
This was already merged on the dev branch on [this commit](https://github.com/alvarotrigo/react-fullpage/commit/2f3e6a13ddd75e1f1fc5d2b9cead9bac55cc7b47)

**Comment by alvarotrigo** [comment]
Thanks anyways! 👍

**Comment by AbobkerElaghel** [comment]
of course, but the master branch still has them required?
and as u know, when you install a package the master branch gets downloaded.

should I Re-open the pull request to the master branch.

**Comment by alvarotrigo** [comment]
Yeap, I'm aware of that.

But we only merge on the dev branch when we have more than one issue fixed. 
Then we create a new release with all of them. It makes it easier to track changes and so on.

I'll merge this into the master when we update react-fullpage to the latest fullpage.js version 4.
In about 2 weeks.

**Pull request closed without merging**
