### PR TITLE
Removed dummy section, added checks for dynamic changes

### PR DESCRIPTION
**Pull request by cmswalker**
@alvarotrigo this should fix https://github.com/alvarotrigo/react-fullpage/issues/62

and it gets rid of the dummy section

However I'm having issues when it comes to including the scrollOverflow extension, it breaks as it can't find a classList of undefined. Could you look into why this might happen? I left a note [here](https://github.com/alvarotrigo/react-fullpage/pull/66/files#diff-893e28c84227405e175afc228592b151L5)

### CODE REVIEW

**Comment by alvarotrigo** [comment]
Thanks for taking a second look at the dummy section issue! 👍 

I noticed you are checking for the amount of sections and slides in order to define whether to destroy and re-initialise fullpage.js.

Just one thing, I think you should be checking for `.fp-slide` or `.fp-section` in [line 61 to 72](https://github.com/alvarotrigo/react-fullpage/pull/66/files#diff-ec820133d3a59cce2a3fc5d3facfdc2fR61). Those are the internal classes added by fullPgae.js to identify slides and sections respectively. Bare in mind that `.slide` and `.section` are selectors that can be customised for developers by using the fullpage.js options `sectionSelector` and `slideSelector`. So `.slide` or `.section` won't necessary exist at all. 

One question tho. I guess the component wouldn't update automatically when changing other fullpage.js properties like `sectionsColor` or `anchors` right? 
In that case, is there a way to manually call `componentDidUpdate` ?  (or a new `build` method?)

We have a similar call [in the Vue wrapper](https://github.com/alvarotrigo/vue-fullpage.js#dynamic-changes) for some dynamic changes as well as in the Angular wrapper that still in progress.

**Comment by alvarotrigo** [comment]
> The alternative would be to perform a destroy() and update() after every render but that could be expensive

Yeap.

**Comment by cmswalker** [comment]
@alvarotrigo I've started fixing the root issue for many of these problems. You can see the start of it in this commit https://github.com/alvarotrigo/react-fullpage/pull/66/commits/f6373aa603bfd4f26b634a5cde1d580ba5a30dd4

If i could get a list of all fullpage.js options and their types, I could fix this fairly quickly. It might be a good separate README to add in general to fullpage.js documentation. Something like:

```js
{
	sectionsColor: Array,
	scrollOverflow: Boolean,
	navigation: Boolean,
	...etc
}
```

**Comment by alvarotrigo** [comment]
Looking good!! Thanks for that!

Regarding the types, some can be both String and Array or even String and null. So not sure how you would categorise those. So far, I put them under "Object":

```json
{
    menu: string,
    anchors: Array,
    lockAnchors: Boolean,
    navigation: Boolean,
    navigationPosition: string,
    navigationTooltips: Array, // ['firstSlide', 'secondSlide']
    showActiveTooltip: Boolean,
    slidesNavPosition: string,
    slidesNavigation: Boolean,
    scrollBar: Boolean,
    hybrid: Boolean, 

    //scrolling
    css3: Boolean,
    scrollingSpeed: Number,
    autoScrolling: Boolean,
    fitToSection: Boolean,
    fitToSectionDelay: Number,
    easing: string,
    easingcss3: string,
    loopBottom: Boolean,
    loopTop: Boolean,
    loopHorizontal: Boolean,
    continuousVertical: Boolean,
    continuousHorizontal: Boolean,
    scrollHorizontally: Boolean,
    interlockedSlides: Object, // true, false, [1, 3, 5]
    dragAndMove: Object, //true, false, 'horizontal', 'fingersonly'
    offsetSections: Boolean,
    resetSliders: Boolean,
    fadingEffect: Object, //true, false, 'sections', 'slides'
    normalScrollElements: string, // '#element1, .element2', 
    scrollOverflow: Boolean,
    scrollOverflowReset: Boolean,
    scrollOverflowHandler: Object,
    scrollOverflowOptions: Object,
    touchSensitivity: Number,
    normalScrollElementTouchThreshold: Number,
    bigSectionsDestination: Object, //top, bottom, null 
    
    //Accessibility
    keyboardScrolling: Boolean,
    animateAnchor: Boolean,
    recordHistory: Boolean,


    //Design
    controlArrows: Boolean,
    controlArrowColor: string,
    verticalCentered: Boolean,
    sectionsColor: Array,
    paddingTop: string,
    paddingBottom: string,
    fixedElements: string, // '#header, .footer'
    responsive: Number,
    responsiveWidth: Number,
    responsiveHeight: Number,
    responsiveSlides: Boolean,
    parallax: Object, // true, false, 'sections', 'slides'
    parallaxOptions: {
        percentage: Number,
        property: string,
        type: string,
    },


    //Custom selectors
    sectionSelector: string,
    slideSelector: string,

    //Events
    v2compatible: Boolean,
    afterLoad(): void,
    onLeave: void,
    afterRender(): void,
    afterResize(width: Number, height: Number): void,
    afterReBuild: void,
    afterSlideLoad: void,
    onSlideLeave: void,
    afterResponsive: void,


    lazyLoading: Boolean,
    licenseKey: string,

    /* keys for extensions */
    fadingEffectKey: string,
    responsiveSlidesKey: string,
    continuousHorizontalKey: string,
    interlockedSlidesKey: string,
    scrollHorizontallyKey: string,
    resetSlidersKey: string,
    offsetSectionsKey: string,
    dragAndMoveKey: string,
    parallaxKey: string,
}
```

**Comment by alvarotrigo** [comment]
> However I'm having issues when it comes to including the scrollOverflow extension, it breaks as it can't find a classList of undefined. Could you look into why this might happen? I left a note here

I get the Maximum call stack size exceeded from #38
But that's an issue in fullPage.js that I've solved on the dev branch. Not an issue.

Working great to me! I've merged it on the dev branch and I'll merge it to the mater one now. I'll be releasing a new version as some people is waiting for these fixes.

**Pull request merged**
