### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shahzore-qureshi**
This is a fix for the scrollOverflow functionality not working. I spent hours debugging this, and I realized this CSS file was missing.

### CODE REVIEW

**Comment by cmswalker** [comment]
Yes lets scrap it in example

**Comment by shahzore-qureshi** [comment]
I tried that, but the CSS did not take effect. Ah well. Thanks for the quick response. It's probably an issue on my end.

**Comment by alvarotrigo** [comment]
@shahzore-qureshi did you check if it was building the bundle file properly? Maybe it skipped the CSS inclusion due to lack of npm packages to include it?

**Comment by alvarotrigo** [comment]
> Yes lets scrap it in example

Done! 
I modified the `package.json` and the `webpack.config.js` files in order to solve it and add the CSS on the example build. 
If there's anything you want to change let me know!

**Pull request closed without merging**
